/* AUTO-GENERATED by sw/tools/gen_fixtures_header.py from sw/tools/fixtures.py
 * — DO NOT EDIT BY HAND. Regenerate with:
 *   python3 sw/tools/gen_fixtures_header.py
 *
 * These are the exact X/W byte fixtures NPU-08 requires firmware to write
 * immediately before SUBMIT; sw/tools/mkimage.py computes the independent
 * expected Y words for the *same* arrays from this same fixtures.py module,
 * so there is a single source of truth for the test vectors.
 */
#ifndef OPENCHIP_SW_B1_FIXTURES_H
#define OPENCHIP_SW_B1_FIXTURES_H

#include <stdint.h>

#define B1_Y_SENTINEL_WORD 0x5a5a5a5au
#define B1_EXPECTED_MAGIC   0x42314558u
#define B1_EXPECTED_ABI     1u
#define B1_EXPECTED_CMD_COUNT 2u

/* cmd_a_poll: K=10 N=3 G=4 W_STRIDE=16 TAG=0xa5a50001 */
#define B1_CMD_A_POLL_TAG      0xa5a50001u
#define B1_CMD_A_POLL_K        10u
#define B1_CMD_A_POLL_N        3u
#define B1_CMD_A_POLL_GROUP    4u
#define B1_CMD_A_POLL_W_STRIDE 16u
#define B1_CMD_A_POLL_X_BASE   0x80600000u
#define B1_CMD_A_POLL_W_BASE   0x80600010u
#define B1_CMD_A_POLL_Y_BASE   0x80600040u
#define B1_CMD_A_POLL_Y_WORDS  9u
static const int8_t b1_cmd_a_poll_x[10] = { 127, -128, 5, -5, 3, 64, -64, 1, -1, 100 };
static const int8_t b1_cmd_a_poll_w[48] = { -128, 127, 3, -3, 9, -9, 2, -2, 4, -4, 7, 8, 9, 10, 11, 12, 10, -10, 20, -20, 30, -30, 40, -40, 50, -50, 7, 8, 9, 10, 11, 12, 127, -128, -128, 127, -7, 1, -1, 64, -64, 99, 7, 8, 9, 10, 11, 12 };

/* cmd_b_irq: K=13 N=2 G=8 W_STRIDE=16 TAG=0xa5a50002 */
#define B1_CMD_B_IRQ_TAG      0xa5a50002u
#define B1_CMD_B_IRQ_K        13u
#define B1_CMD_B_IRQ_N        2u
#define B1_CMD_B_IRQ_GROUP    8u
#define B1_CMD_B_IRQ_W_STRIDE 16u
#define B1_CMD_B_IRQ_X_BASE   0x80600100u
#define B1_CMD_B_IRQ_W_BASE   0x80600120u
#define B1_CMD_B_IRQ_Y_BASE   0x80600150u
#define B1_CMD_B_IRQ_Y_WORDS  4u
static const int8_t b1_cmd_b_irq_x[13] = { 127, -128, 3, -3, 7, -7, 127, -128, 11, -11, 13, -13, 50 };
static const int8_t b1_cmd_b_irq_w[32] = { -128, 127, 1, -1, 2, -2, 3, -3, 4, -4, 5, -5, 6, 7, 8, 9, 50, -50, 60, -60, 70, -70, 80, -80, 90, -90, 100, -100, 110, 7, 8, 9 };

#endif /* OPENCHIP_SW_B1_FIXTURES_H */
