// rom.sv -- 64 KiB immutable boot ROM, AXI4 target.
// Spec: docs/spec/llm-soc-v1/system.md §2 address table (base 0x00000000,
// 65536 bytes, CPU R/X, NPU deny) and axi.md AXI-01/02/03/06/08. Region
// permission/decode (R/X vs. deny) is enforced upstream by the fabric
// (SYS-04 "physical source-port identity"); this module only implements
// the target-side read/write protocol and is address-window agnostic
// (it trusts that every request it receives already belongs to its
// window and fits within it, per AXI-02 "no region crossing").
//
// This is a simulation delivery vehicle, not silicon ROM: content comes
// from `rom_data.svh` (generated by gen_rom.py; see hw/rtl/rom/README.md),
// never from `initial`/`$readmemh` (both forbidden by house rules). The
// shipped rom_data.svh is an all-zero placeholder; real firmware content
// is produced later by SW-B1 and dropped in by re-running gen_rom.py.
`default_nettype none

module rom (
    input wire clk,
    input wire rst_n,

    // AXI4 target port (fabric is always the initiator here). Full
    // signal list per AXI-01; USER/REGION are absent (zero-width, not
    // trusted signals) and therefore not present as ports.
    input  wire        s_axi_awvalid,
    output logic        s_axi_awready,
    input  wire [31:0] s_axi_awaddr,
    input  wire [ 1:0] s_axi_awid,
    input  wire [ 7:0] s_axi_awlen,
    input  wire [ 2:0] s_axi_awsize,
    input  wire [ 1:0] s_axi_awburst,
    input  wire        s_axi_awlock,
    input  wire [ 3:0] s_axi_awcache,
    input  wire [ 2:0] s_axi_awprot,
    input  wire [ 3:0] s_axi_awqos,

    input  wire        s_axi_wvalid,
    output logic        s_axi_wready,
    input  wire [31:0] s_axi_wdata,
    input  wire [ 3:0] s_axi_wstrb,
    input  wire        s_axi_wlast,

    output logic        s_axi_bvalid,
    input  wire        s_axi_bready,
    output logic [ 1:0] s_axi_bresp,
    output logic [ 1:0] s_axi_bid,

    input  wire        s_axi_arvalid,
    output logic        s_axi_arready,
    input  wire [31:0] s_axi_araddr,
    input  wire [ 1:0] s_axi_arid,
    input  wire [ 7:0] s_axi_arlen,
    input  wire [ 2:0] s_axi_arsize,
    input  wire [ 1:0] s_axi_arburst,
    input  wire        s_axi_arlock,
    input  wire [ 3:0] s_axi_arcache,
    input  wire [ 2:0] s_axi_arprot,
    input  wire [ 3:0] s_axi_arqos,

    output logic        s_axi_rvalid,
    input  wire        s_axi_rready,
    output logic [31:0] s_axi_rdata,
    output logic [ 1:0] s_axi_rresp,
    output logic [ 1:0] s_axi_rid,
    output logic        s_axi_rlast
);

  localparam int ROM_BYTES = 65536;  // system.md §2: fixed size, never resized
  localparam int WORDS = ROM_BYTES / 4;  // 16384
  localparam int IDX_W = $clog2(WORDS);  // 14
  localparam int IDX_HI = IDX_W + 1;  // 15 (word index occupies addr[15:2])

  // rom_words[0:WORDS-1], a compile-time constant array driven by one
  // continuous `assign` per word (no `initial`, no `$readmemh`); see
  // gen_rom.py / rom_data.svh header for provenance.
  `include "rom_data.svh"

  // AXI-02 restricts DUT initiators to aligned SIZE=2 INCR beats with no
  // region crossing; AWSIZE/AWBURST/AWLOCK/AWCACHE/AWPROT/AWQOS and their
  // AR counterparts (besides ARLEN, used below) are validated upstream by
  // the fabric decode (SYS-04) and the protocol monitor (AXI-07), not by
  // this target. AWLEN is likewise unused: the write-response FSM keys
  // off WLAST rather than a beat count (see below). Sink to keep lint
  // clean.
  wire unused_axi_fields = |{
    s_axi_awlen, s_axi_awsize, s_axi_awburst, s_axi_awlock, s_axi_awcache, s_axi_awprot, s_axi_awqos,
    s_axi_arsize, s_axi_arburst, s_axi_arlock, s_axi_arcache, s_axi_arprot, s_axi_arqos
  };

  // ROM is read-only: a defensively-accepted write (see below) never
  // commits data anywhere, so AWADDR/WDATA/WSTRB carry no meaning here
  // beyond acceptance handshakes. Sink to keep lint clean.
  wire unused_write_payload = |{s_axi_awaddr, s_axi_wdata, s_axi_wstrb};

  // -------------------------------------------------------------------
  // Read channel (AXI-06: respond within 16 cycles of an accepted read;
  // this design responds the cycle after AR is accepted and on every
  // beat thereafter -- well inside the bound).
  // -------------------------------------------------------------------
  logic        r_busy;
  logic [31:0] r_addr;
  logic [ 1:0] r_id;
  logic [ 7:0] r_len;
  logic [ 7:0] r_beat;

  assign s_axi_arready = !r_busy;
  assign s_axi_rvalid  = r_busy;
  assign s_axi_rdata   = rom_words[r_addr[IDX_HI:2]];
  assign s_axi_rresp   = 2'b00;  // OKAY; fabric already authorized this access (SYS-04)
  assign s_axi_rid     = r_id;
  assign s_axi_rlast   = (r_beat == r_len);

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      // SYS-03: reset epoch rule -- no pre-reset response may leak into
      // the new epoch, so every control flop resets, including mid-burst
      // state.
      r_busy <= 1'b0;
      r_addr <= '0;
      r_id   <= '0;
      r_len  <= '0;
      r_beat <= '0;
    end else if (!r_busy) begin
      if (s_axi_arvalid) begin
        r_busy <= 1'b1;
        r_addr <= s_axi_araddr;
        r_id   <= s_axi_arid;
        r_len  <= s_axi_arlen;
        r_beat <= '0;
      end
    end else begin
      if (s_axi_rvalid && s_axi_rready) begin
        if (s_axi_rlast) begin
          r_busy <= 1'b0;
        end else begin
          r_addr <= r_addr + 32'd4;
          r_beat <= r_beat + 8'd1;
        end
      end
    end
  end

  // -------------------------------------------------------------------
  // Write channel -- ROM is read-only (system.md §2: CPU R/X, NPU deny;
  // no W permission exists for any source). The fabric never forwards a
  // write here (SYS-04: "unmapped or unauthorized access ... has no
  // memory/peripheral side effect"). If one arrives anyway (e.g. a
  // protocol-monitor bypass during bring-up/debug), this target accepts
  // the burst so the initiator cannot deadlock (AXI-03: must tolerate/
  // not deadlock on any offered AW/W), makes no memory change, and
  // returns SLVERR. WLAST alone gates the response (not a count against
  // AWLEN), so an early W-before-AW is tolerated by simple backpressure:
  // WREADY stays low until AW is known, which the spec guarantees
  // arrives no later than the first W of the same transaction (AXI-03).
  // -------------------------------------------------------------------
  logic       w_aw_have;
  logic [1:0] w_aw_id;
  logic       w_last_seen;
  logic       w_b_valid;

  assign s_axi_awready = !w_aw_have;
  assign s_axi_wready  = w_aw_have && !w_last_seen;
  assign s_axi_bvalid  = w_b_valid;
  assign s_axi_bid     = w_aw_id;
  assign s_axi_bresp   = 2'b10;  // SLVERR always: ROM is read-only (SYS-04)

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      w_aw_have   <= 1'b0;
      w_aw_id     <= '0;
      w_last_seen <= 1'b0;
      w_b_valid   <= 1'b0;
    end else begin
      if (s_axi_awvalid && s_axi_awready) begin
        w_aw_have <= 1'b1;
        w_aw_id   <= s_axi_awid;
      end
      if (s_axi_wvalid && s_axi_wready && s_axi_wlast) begin
        w_last_seen <= 1'b1;
      end
      if (w_aw_have && w_last_seen && !w_b_valid) begin
        w_b_valid <= 1'b1;  // AXI-03: BVALID follows accepted AW and final W, never earlier
      end
      if (s_axi_bvalid && s_axi_bready) begin
        w_b_valid   <= 1'b0;
        w_aw_have   <= 1'b0;
        w_last_seen <= 1'b0;
      end
    end
  end

endmodule

`default_nettype wire
