#!/usr/bin/env python3
"""Generate sw/common/regmap.h from docs/spec/llm-soc-v1/contract.json.

Source of truth: contract.json `address_regions`, `irqs`, `csr_registers`,
`clock_hz` — see docs/spec/llm-soc-v1/system.md SYS-04, SYS-08, SYS-09..SYS-11
and npu.md NPU-04 for the prose these numbers implement. Any discrepancy
between this generator's output and the prose is a spec defect (AGENTS.md
Iron Rule 1), not something to patch by hand in the generated header.

Usage:
    python3 sw/tools/gen_regmap.py [--contract PATH] [--out PATH]

The generated header is committed; re-run this script whenever
contract.json changes and diff the result.
"""
import argparse
import json
import os
import sys

HEADER_GUARD = "OPENCHIP_SW_COMMON_REGMAP_H"


def c_ident(s: str) -> str:
    return s.upper().replace("-", "_").replace(".", "_")


def field_mask(msb: int, lsb: int) -> int:
    width = msb - lsb + 1
    return ((1 << width) - 1) << lsb


def emit_address_regions(out, regions):
    out.append("/* ---- address_regions (contract.json) ---- */")
    for r in regions:
        rid = c_ident(r["id"])
        out.append(f'#define REGION_{rid}_BASE   0x{r["base"]:08x}u')
        out.append(f'#define REGION_{rid}_SIZE   0x{r["size"]:08x}u')
        out.append(f'#define REGION_{rid}_END    0x{r["end_exclusive"]:08x}u  '
                    f'/* end-exclusive; cpu={r["cpu_permission"]} npu={r["npu_permission"]} target={r["target"]} */')
    out.append("")


def emit_irqs(out, irqs):
    out.append("/* ---- irqs (contract.json): CPU custom-IRQ bit <- peripheral-gated level ---- */")
    for irq in irqs:
        src = c_ident(irq["source"])
        out.append(f'#define IRQ_{src}_CPU_BIT     {irq["cpu_bit"]}u')
        out.append(f'#define IRQ_{src}_SOURCE_BIT  {irq["source_bit"]}u')
        out.append(f'#define IRQ_{src}_CPU_MASK    (1u << {irq["cpu_bit"]})')
        out.append(f'#define IRQ_{src}_SOURCE_MASK (1u << {irq["source_bit"]})')
    out.append("")


def emit_csr_registers(out, regs):
    out.append("/* ---- csr_registers (contract.json) ---- */")
    blocks_seen = {}
    for reg in regs:
        block = c_ident(reg["block"])
        if block not in blocks_seen:
            blocks_seen[block] = reg["address"] - reg["offset"]
    out.append("/* Block base addresses (derived: register address - register offset) */")
    for block, base in blocks_seen.items():
        out.append(f"#define {block}_BASE 0x{base:08x}u")
    out.append("")
    for reg in regs:
        block = c_ident(reg["block"])
        name = c_ident(reg["name"])
        prefix = f"{block}_{name}"
        out.append(f'/* {reg["block"]}.{reg["name"]}: {reg["access"]}, reset=0x{reg["reset"]:x} */')
        out.append(f'#define {prefix}_OFFSET 0x{reg["offset"]:02x}u')
        out.append(f'#define {prefix}_ADDR   ({block}_BASE + {prefix}_OFFSET)')
        out.append(f'#define {prefix}_RESET  0x{reg["reset"]:08x}u')
        for f in reg["fields"]:
            fname = c_ident(f["name"])
            msb, lsb = f["msb"], f["lsb"]
            mask = field_mask(msb, lsb)
            out.append(f'#define {prefix}_{fname}_LSB  {lsb}u')
            out.append(f'#define {prefix}_{fname}_MASK 0x{mask:08x}u')
        out.append("")


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    default_contract = os.path.normpath(
        os.path.join(here, "..", "..", "docs", "spec", "llm-soc-v1", "contract.json"))
    default_out = os.path.normpath(os.path.join(here, "..", "common", "regmap.h"))
    ap.add_argument("--contract", default=default_contract)
    ap.add_argument("--out", default=default_out)
    args = ap.parse_args()

    with open(args.contract) as f:
        d = json.load(f)

    out = []
    out.append("/* AUTO-GENERATED by sw/tools/gen_regmap.py — DO NOT EDIT BY HAND.")
    out.append(f' * Source: docs/spec/llm-soc-v1/contract.json, version {d.get("version")},'
                f' configuration {d.get("configuration")}.')
    out.append(" * Regenerate with: python3 sw/tools/gen_regmap.py")
    out.append(" * contract.json wins for names/numbers; system.md/npu.md prose defines semantics.")
    out.append(" */")
    out.append(f"#ifndef {HEADER_GUARD}")
    out.append(f"#define {HEADER_GUARD}")
    out.append("")
    out.append("/* All content below is plain integer #defines: safe to include from both")
    out.append(" * C and GNU-assembler .S files. stdint.h itself is C-only. */")
    out.append("#ifndef __ASSEMBLER__")
    out.append("#include <stdint.h>")
    out.append("#endif")
    out.append("")
    out.append(f'#define SIM_CLOCK_HZ {d["clock_hz"]}u')
    out.append("")

    emit_address_regions(out, d["address_regions"])
    emit_irqs(out, d["irqs"])
    emit_csr_registers(out, d["csr_registers"])

    out.append(f"#endif /* {HEADER_GUARD} */")
    out.append("")

    text = "\n".join(out)
    with open(args.out, "w") as f:
        f.write(text)
    print(f"wrote {args.out} ({len(text)} bytes, "
          f"{len(d['address_regions'])} regions, {len(d['irqs'])} irqs, "
          f"{len(d['csr_registers'])} registers)")


if __name__ == "__main__":
    main()
