#!/usr/bin/env python3
"""sw/tools/gen_fixtures_header.py — emit sw/b1/fixtures.h from
sw/tools/fixtures.py, so the exact X/W bytes firmware writes to the NPU
descriptor (NPU-08 "write immutable X/W bytes") are generated from the same
single Python source that sw/tools/mkimage.py uses to compute the
independent expected Y words — no hand-copied literal table can drift
between the firmware image and the host-computed expectation.
"""
import argparse
import os

import fixtures as fx


def c_array_i8(name, values):
    body = ", ".join(str(v) for v in values)
    return f"static const int8_t {name}[{len(values)}] = {{ {body} }};"


def emit_command(cmd):
    out = []
    upper = cmd["name"].upper()
    out.append(f"/* {cmd['name']}: K={cmd['k']} N={cmd['n']} G={cmd['group']} "
                f"W_STRIDE={cmd['w_stride']} TAG=0x{cmd['tag']:08x} */")
    out.append(f"#define B1_{upper}_TAG      0x{cmd['tag']:08x}u")
    out.append(f"#define B1_{upper}_K        {cmd['k']}u")
    out.append(f"#define B1_{upper}_N        {cmd['n']}u")
    out.append(f"#define B1_{upper}_GROUP    {cmd['group']}u")
    out.append(f"#define B1_{upper}_W_STRIDE {cmd['w_stride']}u")
    out.append(f"#define B1_{upper}_X_BASE   0x{cmd['x_base']:08x}u")
    out.append(f"#define B1_{upper}_W_BASE   0x{cmd['w_base']:08x}u")
    out.append(f"#define B1_{upper}_Y_BASE   0x{cmd['y_base']:08x}u")
    word_count = fx.command_y_word_count(cmd)
    out.append(f"#define B1_{upper}_Y_WORDS  {word_count}u")
    out.append(c_array_i8(f"b1_{cmd['name']}_x", cmd["x"]))
    w_flat = [v for row in cmd["w_rows"] for v in row]
    out.append(c_array_i8(f"b1_{cmd['name']}_w", w_flat))
    out.append("")
    return "\n".join(out)


def main():
    ap = argparse.ArgumentParser()
    here = os.path.dirname(os.path.abspath(__file__))
    default_out = os.path.normpath(os.path.join(here, "..", "b1", "fixtures.h"))
    ap.add_argument("--out", default=default_out)
    args = ap.parse_args()

    out = []
    out.append("/* AUTO-GENERATED by sw/tools/gen_fixtures_header.py from sw/tools/fixtures.py")
    out.append(" * — DO NOT EDIT BY HAND. Regenerate with:")
    out.append(" *   python3 sw/tools/gen_fixtures_header.py")
    out.append(" *")
    out.append(" * These are the exact X/W byte fixtures NPU-08 requires firmware to write")
    out.append(" * immediately before SUBMIT; sw/tools/mkimage.py computes the independent")
    out.append(" * expected Y words for the *same* arrays from this same fixtures.py module,")
    out.append(" * so there is a single source of truth for the test vectors.")
    out.append(" */")
    out.append("#ifndef OPENCHIP_SW_B1_FIXTURES_H")
    out.append("#define OPENCHIP_SW_B1_FIXTURES_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("")
    out.append(f"#define B1_Y_SENTINEL_WORD 0x{fx.Y_SENTINEL_WORD:08x}u")
    out.append(f"#define B1_EXPECTED_MAGIC   0x{fx.EXPECTED_MAGIC:08x}u")
    out.append(f"#define B1_EXPECTED_ABI     {fx.EXPECTED_ABI}u")
    out.append(f"#define B1_EXPECTED_CMD_COUNT {len(fx.ALL_COMMANDS)}u")
    out.append("")
    for cmd in fx.ALL_COMMANDS:
        out.append(emit_command(cmd))
    out.append("#endif /* OPENCHIP_SW_B1_FIXTURES_H */")
    out.append("")

    text = "\n".join(out)
    with open(args.out, "w") as f:
        f.write(text)
    print(f"wrote {args.out} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
